---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: kbox
  labels:
    app: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      initContainers:
        - name: init-web
          image: busybox:1.36
          command:
            - sh
            - -c
            - >
              mkdir -p /work &&
              echo ok >/work/index.html &&
              echo ok >/work/health
          volumeMounts:
            - name: webroot
              mountPath: /work
      containers:
        - name: app
          image: ghcr.io/nginxinc/nginx-unprivileged:stable
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - name: webroot
              mountPath: /usr/share/nginx/html
          securityContext:
            runAsNonRoot: true
            runAsUser: 101
      volumes:
        - name: webroot
          persistentVolumeClaim:
            claimName: app-pvc
