---
apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: kbox
  labels:
    app: app
spec:
  selector:
    app: app
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
