apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: kbox
  labels:
    app: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: ghcr.io/nginxinc/nginx-unprivileged:stable
          ports:
            - name: http
              containerPort: 80
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - name: webroot
              mountPath: /usr/share/nginx/html
      volumes:
        - name: webroot
          emptyDir: {}
