---
apiVersion: v1
kind: Pod
metadata:
  name: net-debug
  namespace: kbox
  labels:
    run: net-debug
spec:
  containers:
    - name: bb
      image: busybox:1.36
      command:
        - sh
        - -c
        - sleep 360000
